name = "InlineTest"
uuid = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
